name: Bibbi

on:
  push:
    branches:
      - develop
      - feature/*
      - fix/*
    tags:
      - "v*"
  
jobs:  
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcodebuild-scheme: ['App']
        
    steps:
    
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: latest
            
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Bring Bibbi ignored file with Config
        uses: actions/checkout@v3
        with: 
          repository: depromeet/14th-team5-iOS-ignored
          path: depromeet/14th-team5-iOS/14th-team5-iOS/XCConfig
          token: ${{secrets.ACTION_TOKEN}}

      - name: Tuist Master Key Log # 요기선 정확히 마스터기 값 들어감
        run: |
          echo ${{secrets.MASTER_KEY}} | sed 's/./& /g' 

      - name: Setting Tuist Master Key
        run: | 
          echo -n "$MASTER_KEY" > Tuist/master.key
        env:
          MASTER_KEY: ${{secrets.MASTER_KEY}}
        
      - name: Install Tuist CLI
        run: curl -Ls https://install.tuist.io| bash
        
      - name: Install FastLane 
        run: brew install fastlane
        
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
                
      - name: Tuist Clean Command
        run: tuist clean
      
      - name: Tuist Fetch Command
        run: tuist fetch
        

      - name: Tuist Siging Decrept
        run: tuist signing decrypt
        
      - name: Tuist Keychain Log
        run: |
          echo "KEYCHAIN_NAME: ${{secrets.KEYCHAIN_NAME}}
          echo "KEYCHAIN_PASSWORD: ${{secrets.KEYCHAIN_PASSWORD}}
        env:
            KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      # - name: Fastalne setup Keychain
      #   run: fastlane setup_keychain
      #   env:
      #       KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      #       KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
            

      - name: Tuist generate Command      
        run: |
          echo ${{secrets.MASTER_KEY}} | sed 's/./& /g'
          tuist generate  

      # - name: Tuist Build Command
      #   run: tuist build
                  
      # - run: fastlane upload_dev_to_testflight
      #   env:
      #     KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
      #     APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      #     APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}


    
      
      # - name: bibbi app scheme output # Bibbi App Scheme Output Code
      #   run: xcodebuild -list -workspace "Bibbi.xcworkspace"
        
      # - name: xcode build App 🛠️ # Bibbi App Build
      #   run: xcodebuild clean build -workspace "./Bibbi.xcworkspace" -scheme "${{ matrix.xcodebuild-scheme }}" -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=latest"
     
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

