name: Bibbi

on:
  push:
    branches:
      - develop
      - feature/*
    tags:
      - "v*"
  
jobs:  
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcodebuild-scheme: ['App', 'WidgetExtension']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Install Tuist CLI
        run: curl -Ls https://install.tuist.io | bash
        
      - name: Tuist Clean Command
        run: tuist clean

      - name: Tuist Fetch Command
        run: tuist fetch

      - name: Tuist generate Command
        run: tuist generate

      - name: Tuist Build Command
        run: tuist build      
      
      - name: bibbi app scheme output # Bibbi App Scheme Output Code
        run: xcodebuild -list -workspace "Bibbi.xcworkspace"
        
      # - name: xcode build App 🛠️ # Bibbi App Build
      #   run: xcodebuild clean build -workspace "Bibbi.xcworkspace" -scheme "${{ matrix.xcodebuild-scheme }}" -destination "platform=iOS Simulator,name=iPhone 13 mini,OS=latest"
     
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  # deploy:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: fastlane deploy start
  #     run: echo "fastlane deploy start"
  #     env:
  #       APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
  #       APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
  #       APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
